### PR TITLE
Added codename configuration, added architecture in .deb file name

### PR DESCRIPTION
**Pull request by samuelebistoletti**
I have made some modifications in order to have .deb packages prepared with distribution codename chained with version, so it can be possible to build the same release for different distribution (ex. with Docker containers). I also added the architecture in the package filename. I also fixed a warning of unused import.

### CODE REVIEW

**Comment by johnhamelink** [comment]
Hi @samuelebistoletti, thanks for this!

 - Can you rebase this PR against master so your previous work on Systemd isn't part of this PR?
 - Please excuse my ignorance, but can you describe to the uninitiated the use-case for a codename and what makes it different from a version number?

**Comment by samuelebistoletti** [comment]
I rebased the the repo with master, now should be ok.
I also added some details to explain codename on the README.

**Comment by samuelebistoletti** [comment]
Hi,
any news about the possibility to merge that?

Thanks

**Comment by johnhamelink** [comment]
Hey @samuelebistoletti sorry for lack of response - been super busy! Looks like we're good to go (the credo errors are project-wide and need to be fixed in another PR!)

JH

**Pull request merged**
