### PR TITLE
Update timex to 3.0.4

### PR DESCRIPTION
**Pull request by eraserewind**

### CODE REVIEW

**Comment by johnhamelink** [comment]
@eraserewind This PR created compilation errors. Could you have another look at it?

**Comment by eraserewind** [comment]
So timex 3.x depends on Elixir 1.3+ (because of the new Date/DateTime API).

I've bumped the required Elixir version to 1.3, but I don't know if that's enough to update Travis.

**Comment by johnhamelink** [comment]
@eraserewind thanks! Merged 😄

**Comment by eraserewind** [comment]
💓

**Pull request merged**
