### PR TITLE
use erl_tar instead of system (g)tar

### PR DESCRIPTION
**Pull request by tverlaan**
So here it is. Tests still run and the package still installs. With erl_tar it's not possible to set the owner so I've removed that.

### CODE REVIEW

**Comment by johnhamelink** [comment]
@tverlaan cool! Have you tested installing using your PR? Without the ability to set the owner I worry that there will be permissions errors when actually running the release on a server?

**Comment by tverlaan** [comment]
I've tested it on 1 machine and that worked. Not sure if that is sufficient so I'll test some more.

**Comment by johnhamelink** [comment]
Thanks @tverlaan - lets sit on it for a while and if we don't hear anything more, then LGTM :rocket:

**Comment by tverlaan** [comment]
Hi @johnhamelink, I got a hint from the author of debbie to use `swab` to set fakeroot :-)
I had to make some other changes to make the tar file more correct according to swab. It complained about the file header as long as I included directories 'usr', 'opt' and 'etc' and listed all files in erl_tar.

Anyway, it works now and I think it's pretty cool.

**Comment by johnhamelink** [comment]
@tverlaan interesting! I'll give this a go :smile: If it works for me I'll merge. Thanks for your work so far by the way!

**Edit:** so I ran `exrm --deb` on `exrm_deb` to produce a deb file - that works fine, however after running `lintian` on it, I see there are errors surrounding ownership & permissions:

```
W: exrmdeb: changelog-not-compressed-with-max-compression changelog.gz
E: exrmdeb: file-in-etc-not-marked-as-conffile etc/init/exrmdeb.conf
E: exrmdeb: file-in-etc-not-marked-as-conffile etc/systemd/system/multi-user.target.wants/exrmdeb.service
E: exrmdeb: control-file-has-bad-permissions preinst 0644 != 0755
E: exrmdeb: control-file-has-bad-owner preinst 1000/1000 != root/root
```

About lintian - there is a lot of noise in the tool because it doesn't like things to be put in the `opt` directory. I'll also happily admit that I don't understand all of the errors it spits out.

The way I'm sorting out "errors I think we care about" with "errors I don't think we care about", within this context, is whether the error concerns things that are not in the `opt` directory.

I think I'll merge this and open an issue with all of the leftover lintian errors.

**Comment by tverlaan** [comment]
Hi @johnhamelink,

After some digging I found out that erl_tar produces slightly different tar files then the system tar. It doesn't create the directories in the tar file which causes installation errors. I think you didn't ran into this so I'm wondering if you could test that by installing the deb on a 'fresh' system? If so we need to look at fixing erl_tar or see if there is another library that has solved this already.

system tar:

```
./
./etc/
./etc/init/
./etc/init/exrmdeb.conf
./etc/systemd/
./etc/systemd/system/
./etc/systemd/system/multi-user.target.wants/
./etc/systemd/system/multi-user.target.wants/exrmdeb.service
./opt/
./opt/exrm_deb/
```

erl_tar:

```
etc/init/exrmdeb.conf
opt/exrm_deb/erts-7.3/bin/erl
opt/exrm_deb/erts-7.3/bin/erlc
opt/exrm_deb/erts-7.3/bin/epmd
opt/exrm_deb/erts-7.3/bin/start
opt/exrm_deb/erts-7.3/bin/heart
opt/exrm_deb/erts-7.3/bin/ct_run
opt/exrm_deb/erts-7.3/bin/run_erl
opt/exrm_deb/erts-7.3/bin/escript
opt/exrm_deb/erts-7.3/bin/erlexec
```

It doesn't matter if I add a directory or all files by recursively finding them because that is what erl_tar does when it sees a directory.
If I add an empty directory then `swab` doesn't treat it as a valid tar file so I'm unable to set fakeroot. `swab` is however capable of setting fakeroot on a normal tar file.

Anyway, if you're not having issues we can leave this for the time be. Otherwise we should maybe revert and create a better patch.

**Pull request merged**
